#!/bin/bash
# Insert modal before PasswordModal

awk '
BEGIN { printed = 0 }
/{ \/\* ALL MODAL ESCROW PORTALS \*\/ }/ {
    if (!printed) {
        print "      {showEscrowCalculationModal && ("
        print "        <div className=\"fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200\">"
        print "          <div className=\"bg-white dark:bg-[#18191a] w-full max-w-sm rounded-3xl shadow-2xl border border-gray-200 dark:border-zinc-800 overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-200\">"
        print "            <div className=\"p-4 border-b border-gray-100 dark:border-zinc-800 flex justify-between items-center bg-gray-50/50 dark:bg-zinc-900/50\">"
        print "              <h2 className=\"font-black text-gray-900 dark:text-white text-sm flex items-center gap-2\">"
        print "                {escrowModalStage === \"calculation\" ? ("
        print "                  <><span>🧮</span> Escrow Calculation</>"
        print "                ) : ("
        print "                  <><span>🚀</span> Publish Challenge</>"
        print "                )}"
        print "              </h2>"
        print "              <button "
        print "                onClick={() => {"
        print "                  setShowEscrowCalculationModal(false);"
        print "                  setTimeout(() => setEscrowModalStage(\"calculation\"), 300);"
        print "                }} "
        print "                className=\"text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 cursor-pointer\""
        print "              >"
        print "                <svg className=\"w-5 h-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M6 18L18 6M6 6l12 12\" /></svg>"
        print "              </button>"
        print "            </div>"
        print "            "
        print "            <div className=\"p-4 overflow-y-auto space-y-3 font-sans\">"
        print "              {escrowModalStage === \"calculation\" ? ("
        print "                <>"
        print "                  {escrowEngineTab === \"mimi\" && ("
        print "                    <div className=\"space-y-2\">"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Contract Value</span>"
        print "                        <span className=\"font-black text-blue-600 dark:text-blue-400\">${getCentralCalculation().contractValue.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Your Req. Stake</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${getCentralCalculation().userStake.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Opponent Req. Stake</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${getCentralCalculation().opponentStake.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Escrow Fee</span>"
        print "                        <span className=\"font-black text-rose-500\">${getCentralCalculation().escrowFee.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Fee Per Player</span>"
        print "                        <span className=\"font-black text-rose-500\">${getCentralCalculation().feePerParticipant.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Winner Receives</span>"
        print "                        <span className=\"font-black text-emerald-600 dark:text-emerald-400\">${getCentralCalculation().escrowLockValue.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Your Outcome</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">{ratioOddName}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Opponent Outcome</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">{opponentSelection === \"1\" ? \"Home\" : opponentSelection === \"X\" ? \"Draw\" : \"Away\"}</span>"
        print "                      </div>"
        print "                    </div>"
        print "                  )}"
        print ""
        print "                  {escrowEngineTab === \"three_way\" && ("
        print "                    <div className=\"space-y-2\">"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Contract Value</span>"
        print "                        <span className=\"font-black text-blue-600 dark:text-blue-400\">${getCentralCalculation().contractValue.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Home Req. Stake</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${ratioOddName === \"1\" ? getCentralCalculation().player1Stake.toFixed(2) : getCentralCalculation().player2Stake.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Draw Req. Stake</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${ratioOddName === \"X\" ? getCentralCalculation().player1Stake.toFixed(2) : getCentralCalculation().player3Stake.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Away Req. Stake</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${ratioOddName === \"2\" ? getCentralCalculation().player1Stake.toFixed(2) : getCentralCalculation().player2Stake.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Escrow Fee</span>"
        print "                        <span className=\"font-black text-rose-500\">${getCentralCalculation().escrowFee.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Fee Per Player</span>"
        print "                        <span className=\"font-black text-rose-500\">${getCentralCalculation().feePerParticipant.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Winner Receives</span>"
        print "                        <span className=\"font-black text-emerald-600 dark:text-emerald-400\">${getCentralCalculation().escrowLockValue.toFixed(2)}</span>"
        print "                      </div>"
        print "                    </div>"
        print "                  )}"
        print ""
        print "                  {escrowEngineTab === \"tujengane\" && ("
        print "                    <div className=\"space-y-2\">"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Contract Value</span>"
        print "                        <span className=\"font-black text-blue-600 dark:text-blue-400\">${getCentralCalculation().contractValue.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Group Target Stake</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${getCentralCalculation().player1Stake.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Est. Contributors</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">{Math.max(1, tujenganeMinContrib)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Est. Contrib/Member</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${(getCentralCalculation().player1Stake / Math.max(1, tujenganeMinContrib)).toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Opponent 1 Stake</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${getCentralCalculation().player2Stake.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Opponent 2 Stake</span>"
        print "                        <span className=\"font-black text-gray-900 dark:text-white\">${getCentralCalculation().player3Stake.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Escrow Fee</span>"
        print "                        <span className=\"font-black text-rose-500\">${getCentralCalculation().escrowFee.toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5 border-b border-gray-100 dark:border-zinc-800\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Fee Per Side</span>"
        print "                        <span className=\"font-black text-rose-500\">${(getCentralCalculation().escrowFee / 3).toFixed(2)}</span>"
        print "                      </div>"
        print "                      <div className=\"flex justify-between text-xs py-1.5\">"
        print "                        <span className=\"text-gray-500 font-bold uppercase\">Winner Receives</span>"
        print "                        <span className=\"font-black text-emerald-600 dark:text-emerald-400\">${getCentralCalculation().escrowLockValue.toFixed(2)}</span>"
        print "                      </div>"
        print "                    </div>"
        print "                  )}"
        print "                </>"
        print "              ) : ("
        print "                <div className=\"space-y-3 py-2\">"
        print "                  <div className=\"text-xs text-gray-500 text-center mb-4\">"
        print "                    Your escrow contract is ready. How would you like to proceed?"
        print "                  </div>"
        print "                  "
        print "                  <button onClick={() => {"
        print "                    window.alert(\"🤖 Nyota AI is now actively searching the global market for compatible pool contributors and opponents.\");"
        print "                    setShowEscrowCalculationModal(false);"
        print "                    setTimeout(() => setEscrowModalStage(\"calculation\"), 300);"
        print "                  }} className=\"w-full bg-indigo-50 dark:bg-indigo-900/20 hover:bg-indigo-100 dark:hover:bg-indigo-900/40 text-indigo-700 dark:text-indigo-400 border border-indigo-200 dark:border-indigo-800/50 py-3 rounded-xl font-bold text-xs flex items-center justify-center gap-2 transition-colors cursor-pointer\">"
        print "                    <span className=\"text-base\">🤖</span> Start Nyota Search"
        print "                  </button>"
        print ""
        print "                  <button onClick={() => {"
        print "                    window.alert(\"Opening contact list...\");"
        print "                    setShowEscrowCalculationModal(false);"
        print "                    setTimeout(() => setEscrowModalStage(\"calculation\"), 300);"
        print "                  }} className=\"w-full bg-blue-50 dark:bg-blue-900/20 hover:bg-blue-100 dark:hover:bg-blue-900/40 text-blue-700 dark:text-blue-400 border border-blue-200 dark:border-blue-800/50 py-3 rounded-xl font-bold text-xs flex items-center justify-center gap-2 transition-colors cursor-pointer\">"
        print "                    <span className=\"text-base\">👤</span> Invite Friend(s)"
        print "                  </button>"
        print ""
        print "                  <button onClick={() => {"
        print "                    window.alert(\"Challenge posted to Global Feed!\");"
        print "                    setShowEscrowCalculationModal(false);"
        print "                    setTimeout(() => setEscrowModalStage(\"calculation\"), 300);"
        print "                  }} className=\"w-full bg-gray-50 dark:bg-zinc-800/50 hover:bg-gray-100 dark:hover:bg-zinc-800 text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-zinc-700 py-3 rounded-xl font-bold text-xs flex items-center justify-center gap-2 transition-colors cursor-pointer\">"
        print "                    <span className=\"text-base\">📢</span> Post Challenge"
        print "                  </button>"
        print "                </div>"
        print "              )}"
        print "            </div>"
        print "            "
        print "            <div className=\"p-4 border-t border-gray-100 dark:border-zinc-800 flex gap-3 bg-gray-50/50 dark:bg-zinc-900/50\">"
        print "               <button "
        print "                 onClick={() => {"
        print "                   if (escrowModalStage === \"actions\") {"
        print "                     setEscrowModalStage(\"calculation\");"
        print "                   } else {"
        print "                     setShowEscrowCalculationModal(false);"
        print "                     setTimeout(() => setEscrowModalStage(\"calculation\"), 300);"
        print "                   }"
        print "                 }} "
        print "                 className=\"flex-1 py-2.5 rounded-xl font-bold text-xs bg-white dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-zinc-700 transition-colors cursor-pointer\""
        print "               >"
        print "                 Back"
        print "               </button>"
        print "               {escrowModalStage === \"calculation\" && ("
        print "                 <button "
        print "                   onClick={() => setEscrowModalStage('\''actions'\'')} "
        print "                   className=\"flex-1 py-2.5 rounded-xl font-bold text-xs bg-emerald-600 hover:bg-emerald-700 text-white shadow-md transition-colors cursor-pointer\""
        print "                 >"
        print "                   Continue"
        print "                 </button>"
        print "               )}"
        print "            </div>"
        print "          </div>"
        print "        </div>"
        print "      )}"
        print ""
        printed = 1
    }
}
{ print }
' src/App.tsx > src/App.tsx.tmp && mv src/App.tsx.tmp src/App.tsx
